apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hasura
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: example-local-env
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/example-hasura.git
    targetRevision: v0.11.0
    helm:
      version: v3
  destination:
    namespace: example-local-env
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
