---
# Source: example-todo-model-service-promote/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-todo-model-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-local-env
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/example-todo-model-service.git
    targetRevision: v0.14.1
    helm:
      version: v3
      values: |
        
        # Set from promote job of CloudNativeEntrepreneur/example-todo-model-service
        local: true
        
  destination:
    namespace: example-local-env
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
