apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-todo-model-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-local-env
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/example-todo-model-service.git
    targetRevision: v0.13.4
    helm:
      version: v3
      values: |
        local: true
  destination:
    namespace: example-local-env
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
