apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-readmodel-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-local-env
  source:
    path: charts/example-readmodel
    repoURL: https://github.com/cloudnativeentrepreneur/example-readmodel-db.git
    targetRevision: HEAD
    helm:
      version: v3
  destination:
    namespace: example-local-env
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

