---
# Source: example-readmodel-db-promote/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-readmodel-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-local-env
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/example-readmodel-db.git
    targetRevision: v0.5.1
    helm:
      version: v3
  destination:
    namespace: example-local-env
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
